name: Date and Time

on:
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    outputs:
      datetime_value: ${{ steps.datetime.outputs.datetime }}
    steps:
      - name: Get Date and Time
        id: datetime
        uses: ajayg2808/datetime@v1.2.0
        with:
          format: 'YYYY-MM-DD HH:mm:ss'
          timezone: "UTC" 

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: Use Date and Time from Job 1
        run: echo "Date and Time:${{ needs.job_1.outputs.datetime_value }}"
