name: Pull Request Workflow

on:
  pull_request:

jobs:
    pull-request-job:
      runs-on: ubuntu-latest
      steps:
        - name: Print pull Request Trigger 
          run: echo "This Workflow is Trigger When a pull Request is a opaned"
